openapi: 3.0.0
info:
  title: Test API
  description: This is an example of using OAuth2 Password Flow in a specification
    to describe security to your API.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/darkside-company/test_api/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- password:
  - read
  - write
tags:
- name: New Tag 1
paths:
  /example:
    get:
      summary: Server example operation
      description: This is an example operation to show how security is applied to
        the call.
      operationId: exampleGET
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Default
  /ping:
    get:
      summary: Server heartbeat operation
      description: "This operation shows how to override the global security defined\
        \ above, as we want to open it up for all users."
      operationId: pingGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
  /test:
    get:
      summary: Test
      description: test
      operationId: testGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
    post:
      summary: Post Test
      description: descr
      operationId: testPOST
      responses:
        "200":
          description: OK
        "404":
          description: not found
      x-swagger-router-controller: Default
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
    Default:
      type: object
      properties:
        id:
          type: integer
          format: int64
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: http://example.com/oauth/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
