name: GitHub Pages Deploy
on:
    push:
        branches:
            - master
            - dev
            - release/*
    pull_request:
        branches:
            - master
            - dev
            - release/*
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  node-version: 16
                  token: ${{ secrets.GITHUB_TOKEN }}

            - run: actions/setup-node@v3

            - name: Download a Build Artifact
              uses: actions/download-artifact@v3.0.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: github-page
                  path: path/to/artifact/

            # - uses: actions/setup-node@v3

            - name: npm install, build, and test
              run: npm install

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  shell: bash
                  name: github-pages
                  path: |
                      dist
                      !dist/**/*.md
                      path/to/artifact/
