on:
    push:
        branches:
            - master
            - dev
            - release/*
    pull_request:
        branches:
            - master
            - dev
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              name: Create File
            - uses: actions/setup-node@v3
            
            - run: echo ${{ toJSON(github.GITHUB_WORKSPACE) }}
