on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch: 

jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to production server
