name: GitHub Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - release/*
  pull_request:
    branches:
      - master
      - dev
      - release/*

permissions:
  contents: read
  # Needed for the action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir artifact

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > artifact.sh
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3.1.1
        with:
          name: github-pages
          path: artifact
