name: GitHub Pages Deploy

on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch: 

jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: npm install and build
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: npm install
      - run: npm build
 
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
