name: GitHub Pages Deploy

on:
  push:
    branches:
    - master
    - release/*
  workflow_dispatch: 

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        name: npm install and build
        
      - name: install global dependencies
        run: npm install -g express-generator
      - name: start server
        run: node server.js

      # <Not provided for brevity>
      # At a minimum this job should upload artifacts using actions/upload-pages-artifact

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  postbuild:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
      - name: postbuild
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
      - name: finalize   
        run: npm install && npm run start
