name: GitHub Pages Deploy

on:
  push:
    branches:
    - master
    - release/*
  workflow_dispatch: 
  pull_request:




jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate files
      run: mkdir artifact && mkdir artifact2 && cd artifact && ../script/new-artifact.sh
      shell: bash

    - name: Upload Pages artifact
      uses: ./
      with:
        path: artifact

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
          name: github-pages
          path: artifact2

    - name: Extract artifact
      run: tar -xf artifact2/artifact.tar -C artifact2 && rm artifact2/artifact.tar
      shell: bash

    - name: Compare files
      run: diff -qr artifact artifact2
      shell: bash

    - name: Check for absence of symlinks
      run: if [ $(find artifact2 -type l | wc -l) != 0 ]; then echo "Symlinks found"; exit 1; fi
      shell: bash

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Setup Node
      uses: actions/upload-pages-artifact@v1
      with:
        path: artifat-name

    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

