on:
    push:
        branches:
            - master
            - dev
            - release/*
    pull_request:
        branches:
            - master
            - dev
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              name: Create File
            - uses: actions/setup-node@v3
            
            - uses: actions/setup-node@v3
              with:
                token: ${{ toJSON(secrets.GH_TOKEN) }}
                node-version: 16
            
            - name: echo Ref
              run: echo ${{ toJSON( github.ref ) }}
              
#             - name: Upload Artifact
#               run: actions/upload-pages-artifact@v1.0.4
            
            - name: Checkout
              uses: actions/checkout@v3
              with:
                env: CHECK

            - name: echo Ref
              run: echo CHECK VAR ${{ toJSON( CHECK ) }}

            - name: Generate files
              run: mkdir artifact && mkdir artifact2 && cd artifact && ../script/new-artifact.sh
              shell: bash

            - name: Upload Pages artifact
              uses: ./
              with:
                path: artifact

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: github-pages
                  path: artifact2

            - name: Extract artifact
              run: tar -xf artifact2/artifact.tar -C artifact2 && rm artifact2/artifact.tar
              shell: bash

            - name: Compare files
              run: diff -qr artifact artifact2
              shell: bash

            - name: Check for absence of symlinks
              run: if [ $(find artifact2 -type l | wc -l) != 0 ]; then echo "Symlinks found"; exit 1; fi
              shell: bash

            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v3
              with:
                name: my-artifact
                path: path/to/artifact

            - name: Display structure of downloaded files
              run: ls -R
              working-directory: path/to/artifact

            - uses: actions/download-artifact@v3
              with:
                  name: my-artifact
                  path: ~/download/path


            - uses: actions/checkout@v2
            - uses: actions/download-artifact@v3
              with:
                path: path/to/artifacts

            - name: Display structure of downloaded files
              run: ls -R
              working-directory: path/to/artifacts
