name: GitHub Pages Deploy
on:
    push:
        branches:
            - master
            - dev
            - release/*
    pull_request:
        branches:
            - master
            - dev
    workflow_dispatch:
        cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: "12"
            - run: npm install
            - run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Save public folder
              uses: actions/upload-artifact@v2
              with:
                  name: public
                  path: public

            - run: echo ${{ toJSON(github) }}

    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: npm install, build, and test
              run: |
                  npm install
                  npm npm test
                  npm start
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  shell: bash
                  name: dist-without-markdown
                  path: |
                      dist
                      !dist/**/*.md

            - name: Archive code coverage results
              uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: output/test/code-coverage.html

            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  node-version: 16
                  working-directory: scripts

            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: my-artifact
                  path: path/to/artifact
              env:
                  MY_ART: my-artifact

            - name: echo $MY_ART ${{ $MY_ART }}
