name: GitHub Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - release/*
  pull_request:
    branches:
      - master
      - dev
      - release/*

permissions:
  contents: read
  # Needed for the action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Create a temporary artifact downloads folder
        run: |
          mkdir path && cd path
          mkdir to && cd to
          mkdir artifact && cd artifact

      - name: Add artifacts to publish to the temp folder
        run: |
          cd path/to/artifact/
          echo 'alpha' >  github-pages
          cd ../../../

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: path/to/artifact/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: github-pages
          # Destination path
          path: path/to/artifact/

      - run: echo "${{ github }}"
          ${{ toJSON(github.workspace) }}


    # Add a dependency to the build job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        run: actions/download-artifact@v3
        
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main

      - run: |
          npm ci
          npm start
